# Generated by Django 2.1.1 on 2019-02-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_files_shenruochen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='website/static/images/%Y/%m/%d/%H/%M/%S/')),
                ('uploader', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Files_shenruochen',
        ),
    ]
